import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

type RuntimeIndex = {
  meta?: {
    activePlayerCharacter?: string;
    activePlayerFallbackAction?: SheetAction;
  };
  animations: Record<string, RuntimeAnimation>;
};

type RuntimeAnimation = {
  character: string;
  state: string;
  direction: string;
  nativeFacing: string;
  path: string;
  frameSize: { width: number; height: number };
  frameCount: number;
  fps: number;
  loop: boolean;
  anchor: {
    baselineY?: number | null;
    bodyCenterX?: number | null;
    bodyHeight?: number | null;
    displayBodyHeight?: number | null;
  };
};

type SheetAction = "idle" | "walk" | "attack" | "gather";
type SheetConfig = {
  key: string;
  path: string;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  fps: number;
  repeat: number;
  anchorY: number;
  anchorX: number;
  bodyHeight: number;
  displayBodyHeight?: number;
  nativeFacesRight: boolean;
};

type PlayerSheetConfig = SheetConfig & {
  south?: SheetConfig;
};

const DEFAULT_PLAYER_CHARACTER = "player_wayfarer";
const args = process.argv.slice(2);

function argValue(name: string): string | undefined {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : undefined;
}

async function readJson<T>(filePath: string): Promise<T> {
  return JSON.parse(await readFile(filePath, "utf8")) as T;
}

function textureKey(assetPath: string): string {
  return path.basename(assetPath).replace(/\.[^.]+$/, "");
}

function actionKey(animation: RuntimeAnimation): SheetAction | null {
  if (animation.state === "idle") return "idle";
  if (animation.state === "walk") return "walk";
  if (animation.state === "attack") return "attack";
  if (animation.state === "gather") return "gather";
  return null;
}

function toClientPath(assetPath: string): string {
  return `assets/${assetPath.replace(/\\/g, "/")}`;
}

function toSheetConfig(animation: RuntimeAnimation): SheetConfig {
  return {
    key: textureKey(animation.path),
    path: toClientPath(animation.path),
    frameWidth: animation.frameSize.width,
    frameHeight: animation.frameSize.height,
    frames: animation.frameCount,
    fps: animation.fps,
    repeat: animation.loop ? -1 : 0,
    anchorY: animation.anchor.baselineY ?? animation.frameSize.height - 1,
    anchorX: animation.anchor.bodyCenterX ?? animation.frameSize.width / 2,
    bodyHeight: animation.anchor.bodyHeight ?? animation.frameSize.height,
    displayBodyHeight: animation.anchor.displayBodyHeight ?? undefined,
    nativeFacesRight: animation.nativeFacing === "right",
  };
}

export function renderAnimationClientModule(index: RuntimeIndex): string {
  const playerEntries: Partial<Record<SheetAction, PlayerSheetConfig>> = {};
  const entityEntries: Record<string, Partial<Record<SheetAction, SheetConfig>>> = {};
  const playerCharacter = index.meta?.activePlayerCharacter ?? DEFAULT_PLAYER_CHARACTER;
  const fallbackAction = index.meta?.activePlayerFallbackAction;

  for (const animation of Object.values(index.animations)) {
    const action = actionKey(animation);
    if (!action) continue;

    if (animation.character === playerCharacter) {
      if (animation.direction !== "side" && animation.direction !== "south") continue;
      if (animation.direction === "south") {
        const existing = playerEntries[action];
        if (existing) {
          existing.south = toSheetConfig(animation);
        }
        continue;
      }
      playerEntries[action] = toSheetConfig(animation);
      continue;
    }

    if (animation.direction !== "side") continue;
    entityEntries[animation.character] ??= {};
    entityEntries[animation.character][action] = toSheetConfig(animation);
  }

  for (const required of ["idle", "walk", "attack"] satisfies SheetAction[]) {
    if (!(required in playerEntries) && fallbackAction && playerEntries[fallbackAction]) {
      playerEntries[required] = { ...playerEntries[fallbackAction] };
    }
    if (!(required in playerEntries)) {
      throw new Error(`Runtime index is missing required player animation for ${playerCharacter}: ${required}`);
    }
  }

  return `// Generated by tools/src/animation-sync-client.ts from client/public/assets/index.json.
` +
    `// Do not edit by hand; update the promoted runtime index, then rerun pnpm animation-sync-client.

` +
    `export type SheetAction = "idle" | "walk" | "attack" | "gather";

` +
    `export type SheetConfig = {
` +
    `  key: string;
` +
    `  path: string;
` +
    `  frameWidth: number;
` +
    `  frameHeight: number;
` +
    `  frames: number;
` +
    `  fps: number;
` +
    `  repeat: number;
` +
    `  anchorY: number;
` +
    `  anchorX: number;
` +
    `  bodyHeight: number;
` +
    `  displayBodyHeight?: number;
` +
    `  nativeFacesRight: boolean;
` +
    `};

` +
    `export type PlayerSheetAction = SheetAction;
` +
    `export type PlayerSheetConfig = SheetConfig & {
` +
    `  south?: SheetConfig;
` +
    `};
` +
    `export type EntitySheetConfig = Partial<Record<SheetAction, SheetConfig>>;

` +
    `export const PLAYER_SHEET_CONFIG = ${JSON.stringify(playerEntries, null, 2)} as const satisfies Record<PlayerSheetAction, PlayerSheetConfig>;

` +
    `export const ENTITY_SHEET_CONFIG: Record<string, EntitySheetConfig> = ${JSON.stringify(entityEntries, null, 2)};
`;
}

async function main(): Promise<void> {
  const indexPath = path.resolve(argValue("--index") ?? "client/public/assets/index.json");
  const outputPath = path.resolve(argValue("--output") ?? "client/src/config/animation-assets.ts");
  const index = await readJson<RuntimeIndex>(indexPath);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderAnimationClientModule(index), "utf8");
  console.log(JSON.stringify({ indexPath, outputPath }, null, 2));
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
