import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type AudioEntry = {
  id: string;
  key: string;
  path: string;
  volume: number;
  cooldownMs?: number;
};

type AudioIndex = {
  music?: AudioEntry[];
  sfx?: AudioEntry[];
};

const ROOT = process.cwd();
const INDEX_PATH = resolve(ROOT, "client/public/assets/audio/index.json");
const OUTPUT_PATH = resolve(ROOT, "client/src/config/audio.ts");

function renderAsset(entry: AudioEntry, includeCooldown: boolean): string {
  const lines = [
    `    key: ${JSON.stringify(entry.key)},`,
    `    path: ${JSON.stringify(entry.path)},`,
    `    volume: ${entry.volume},`,
  ];
  if (includeCooldown && entry.cooldownMs != null) {
    lines.push(`    cooldownMs: ${entry.cooldownMs},`);
  }
  return `  ${JSON.stringify(entry.id)}: {\n${lines.join("\n")}\n  },`;
}

function renderAssets(entries: AudioEntry[] | undefined, includeCooldown: boolean): string {
  return (entries ?? []).map((entry) => renderAsset(entry, includeCooldown)).join("\n");
}

function assertUniqueIds(entries: AudioEntry[], kind: string): void {
  const seen = new Set<string>();
  for (const entry of entries) {
    if (seen.has(entry.id)) throw new Error(`${kind}: duplicate id ${entry.id}`);
    seen.add(entry.id);
  }
}

export function renderAudioClientModule(index: AudioIndex): string {
  const music = index.music ?? [];
  const sfx = index.sfx ?? [];
  assertUniqueIds(music, "music");
  assertUniqueIds(sfx, "sfx");

  return `// Generated by tools/src/audio-sync-client.ts from client/public/assets/audio/index.json.
// Do not edit by hand; run pnpm audio:sync.

export type MusicId = string;

export type SfxId = string;

export type SfxPlaybackOptions = {
  cooldownKey?: string;
  detune?: number;
  rate?: number;
  volumeScale?: number;
};

type AudioAsset = {
  key: string;
  path: string;
  volume: number;
};

type SfxAsset = AudioAsset & {
  cooldownMs?: number;
};

export const MUSIC_ASSETS: Record<MusicId, AudioAsset> = {
${renderAssets(music, false)}
};

export const SFX_ASSETS: Record<SfxId, SfxAsset> = {
${renderAssets(sfx, true)}
};

export const SLIME_SQUISH_SFX = {
  attack: "sfx.monster.slime_squish.attack",
  damage: "sfx.monster.slime_squish.damage",
  die: "sfx.monster.slime_squish.die",
  move: "sfx.monster.slime_squish.move",
} as const satisfies Record<string, SfxId>;

export const SLIME_SQUISH_VARIANTS: Record<string, SfxPlaybackOptions> = {
  monster_meadow_slime: { detune: -35, rate: 0.98 },
  monster_dew_slime: { detune: 45, rate: 1.02 },
  monster_blossom_slime: { detune: 85, rate: 1.04 },
  monster_honey_slime: { detune: -80, rate: 0.96 },
};
`;
}

function readIndex(): AudioIndex {
  return JSON.parse(readFileSync(INDEX_PATH, "utf8")) as AudioIndex;
}

function normalize(value: string): string {
  return value.replace(/\r\n/g, "\n");
}

const args = process.argv.slice(2);
const expected = renderAudioClientModule(readIndex());

if (args.includes("--check")) {
  const actual = normalize(readFileSync(OUTPUT_PATH, "utf8"));
  if (actual !== expected) {
    console.error("audio index: client/src/config/audio.ts is stale; run pnpm audio:sync");
    process.exit(1);
  }
  console.log("[audio-sync] OK — client audio config matches audio index.");
} else {
  writeFileSync(OUTPUT_PATH, expected);
  console.log("[audio-sync] Wrote client/src/config/audio.ts");
}
