/**
 * Reads promoted-registry.json and generates client/src/config/promoted-assets.ts
 * with tile, decal, prop, and sprite path mappings for BootScene to load.
 *
 * Usage: pnpm promoted-asset-sync [--registry <path>] [--output <path>]
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { pruneRegistryEntriesMissingRuntimeFiles } from "./promoted-registry.js";

type PromotedEntry = {
  assetId: string;
  sourcePath: string;
  targetPath: string;
  targetName: string;
  type: string;
  context: string;
  kind: string;
  category: string;
  image?: { width?: number; height?: number };
  basis?: string;
  promotedAt: string;
  warnings: string[];
};

type PromotedRegistry = {
  promoted: Record<string, PromotedEntry>;
  meta: { lastUpdated?: string; count?: number };
};

function argValue(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag);
  return idx >= 0 && idx + 1 < process.argv.length
    ? process.argv[idx + 1]
    : undefined;
}

async function readJson<T>(filePath: string): Promise<T> {
  return JSON.parse(await readFile(filePath, "utf8")) as T;
}

function renderModule(registry: PromotedRegistry): string {
  const tiles: Record<string, string> = {};
  const decals: Record<string, string> = {};
  const props: Record<string, string> = {};
  const sprites: Record<string, string> = {};
  const audio: Record<string, string> = {};
  const basis1440pDisplayPx: string[] = [];

  for (const entry of Object.values(registry.promoted)) {
    const key = entry.targetName;
    const assetPath = entry.targetPath;
    if (entry.basis === "1440p-display-px") {
      basis1440pDisplayPx.push(key);
    }

    switch (entry.type) {
      case "tile":
      case "ground_tiles":
        tiles[key] = assetPath;
        break;
      case "decal":
        decals[key] = assetPath;
        break;
      case "prop":
        props[key] = assetPath;
        break;
      case "sprite":
      case "icon":
      case "portrait":
        sprites[key] = assetPath;
        break;
      case "bgm":
      case "ambience":
      case "audio":
        audio[key] = assetPath;
        break;
    }
  }

  return (
    `/// <reference types="vite/client" />\n` +
    `// Auto-generated by tools/src/promoted-asset-sync.ts from promoted-registry.json\n` +
    `// Do not edit by hand — re-run: pnpm promoted-asset-sync\n\n` +
    `export const PROMOTED_TILES: Record<string, string> = ${JSON.stringify(tiles, null, 2)};\n\n` +
    `export const PROMOTED_DECALS: Record<string, string> = ${JSON.stringify(decals, null, 2)};\n\n` +
    `export const PROMOTED_PROPS: Record<string, string> = ${JSON.stringify(props, null, 2)};\n\n` +
    `export const PROMOTED_SPRITES: Record<string, string> = ${JSON.stringify(sprites, null, 2)};\n\n` +
    `export const PROMOTED_AUDIO: Record<string, string> = ${JSON.stringify(audio, null, 2)};\n\n` +
    `export const PROMOTED_1440P_BASIS_ASSETS = new Set<string>(${JSON.stringify(basis1440pDisplayPx.sort(), null, 2)});\n\n` +
    `if (import.meta.hot) {\n` +
    `  import.meta.hot.accept(() => undefined);\n` +
    `}\n`
  );
}

async function main(): Promise<void> {
  const registryPath = path.resolve(
    argValue("--registry") ?? "client/public/assets/promoted-registry.json"
  );
  const outputPath = path.resolve(
    argValue("--output") ?? "client/src/config/promoted-assets.ts"
  );
  if (process.argv.includes("--prune-missing")) {
    const publicAssetsRoot = path.resolve(argValue("--public-assets-root") ?? "client/public/assets");
    const pruned = await pruneRegistryEntriesMissingRuntimeFiles(publicAssetsRoot);
    console.log(`Pruned ${pruned.removed.length} promoted-registry entries with missing runtime files.`);
    if (pruned.removed.length) console.log(JSON.stringify(pruned.removed, null, 2));
  }

  let registry: PromotedRegistry;
  try {
    registry = await readJson<PromotedRegistry>(registryPath);
  } catch {
    registry = { promoted: {}, meta: {} };
    console.log("No promoted-registry.json found, generating empty module.");
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderModule(registry), "utf8");

  const counts = {
    tiles: Object.values(registry.promoted).filter(
      (e) => e.type === "tile" || e.type === "ground_tiles"
    ).length,
    decals: Object.values(registry.promoted).filter((e) => e.type === "decal")
      .length,
    props: Object.values(registry.promoted).filter((e) => e.type === "prop")
      .length,
    sprites: Object.values(registry.promoted).filter((e) =>
      ["sprite", "icon", "portrait"].includes(e.type)
    ).length,
    audio: Object.values(registry.promoted).filter((e) =>
      ["bgm", "ambience", "audio"].includes(e.type)
    ).length,
  };

  console.log(
    `Synced ${Object.keys(registry.promoted).length} promoted assets → ${outputPath}`
  );
  console.log(JSON.stringify(counts, null, 2));
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
